name: Check Disk Space on Multiple OS

on:
  workflow_dispatch:

jobs:
  check-disk-space:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, macos-latest, windows-latest]

    steps:
      - name: Print Disk Space
        run: |
          df -h /
