name: Google Oem Dumps

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Image download url'
        required: false
        default: 'caiman'

env:
  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  USER_NAME: ${{ secrets.USER_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  SF_PWD: ${{ secrets.SF_PWD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Setup SSH Keys and known_hosts 
        uses: webfactory/ssh-agent@v0.9.1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nikgapps
          password: ${{ secrets.AUTH }}

      - name: Pull latest Docker image
        run: docker pull ghcr.io/nikgapps/afe:latest
  
      - name: Extract file name from URL
        id: extract_filename
        run: |
          url="${{ github.event.inputs.url }}"
          # Split URL by '/'
          IFS='/' read -r -a url_parts <<< "$url"
          # Loop through the parts and find the one containing '.zip'
          for part in "${url_parts[@]}"; do
            if [[ "$part" == *.zip ]]; then
              filename="$part"
              break
            fi
          done
          echo "url=${url}"
          echo "filename=${filename}"
          # Use the new method to set outputs
          echo "filename=$filename" >> $GITHUB_OUTPUT

      - name: Extracting ${{ steps.extract_filename.outputs.filename }}
        run: |
          mkdir workspace
          cd workspace
          echo "Extracting ${{ steps.extract_filename.outputs.filename }}"
          docker run --rm \
          -e GITLAB_TOKEN="${{ secrets.GITLAB_TOKEN }}" \
          -e URL="${{ github.event.inputs.url }}" \
          ghcr.io/nikgapps/afe:latest /usr/src/workdir/run.sh
          cd ..
