name: Dump Test

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Image download url'
        required: false
        default: 'https://dl.google.com/dl/android/aosp/caiman-ota-ad1a.240905.004-36913b8a.zip'

env:
  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  USER_NAME: ${{ secrets.USER_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  SF_PWD: ${{ secrets.SF_PWD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup SSH Keys and known_hosts 
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nikgapps
          password: ${{ secrets.AUTH }}
  
      - name: Pull latest Docker image
        run: docker pull ghcr.io/nikgapps/afe:latest
  
      - name: Testing Docker
        run: |
          mkdir workspace
          cd workspace
          echo "Testing Docker"
          docker run --rm \
          -e GITLAB_TOKEN="${{ secrets.GITLAB_TOKEN }}" \
          -e URL="${{ github.event.inputs.url }}" \
          ghcr.io/nikgapps/afe:latest /usr/src/workdir/run.sh
          cd ..
      
