name: Dynamic Batch Execution Example

on:
  workflow_dispatch:

jobs:
  generate_batches:
    name: Generate Batches
    runs-on: macos-latest

    outputs:
      batch_matrix: ${{ steps.run_python.outputs.batch_matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH Keys and known_hosts 
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      # - name: Setup SSH Keys and known_hosts using kielabokkie
      #   uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ssh-host: gitlab.com

      # - name: Setup SSH keys and known hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     echo "gitlab.com" > ~/.ssh/known_hosts
      #     chmod 644 ~/.ssh/known_hosts
      #     # Start the SSH agent
      #     eval $(ssh-agent)
      #     # Add the SSH private key to the SSH agent
      #     ssh-add ~/.ssh/id_rsa
          
      - name: Add hosts to known_hosts if missing
        run: |
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts  

      - name: Initialization and Fetching the Source Code
        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$EMAIL"
          
      - name: Update Git configs
        run: |
          git config --global http.postBuffer 157286400
          git clone --depth=1 git@github.com:nikgapps/updater.git

      - name: Installing Requirements
        run: |
          python3 -m pip install wheel setuptools testresources lxml
          cd updater
          pip3 install -r requirements.txt
          cd ..
          
      - name: Run Python program to generate batches
        id: run_python
        run: |
          cd updater
          python3 generate_batches.py > batches.json
          echo "::set-output name=batch_matrix::$(cat batches.json)"
      
      # - name: Cleanup known_hosts file
      #   run: |
      #     sed -i '/^frs\.sourceforge\.net /d' ~/.ssh/known_hosts
      #     sed -i '/^gitlab\.com /d' ~/.ssh/known_hosts

  execute_batches:
    name: Execute Batches
    runs-on: macos-latest
    needs: generate_batches

    strategy:
      matrix:
        batch: ${{fromJson(needs.generate_batches.outputs.batch_matrix)}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Keys and known_hosts 
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      # - name: Setup SSH keys and known hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     echo "gitlab.com" > ~/.ssh/known_hosts
      #     chmod 644 ~/.ssh/known_hosts
      #     # Start the SSH agent
      #     eval $(ssh-agent)
      #     # Add the SSH private key to the SSH agent
      #     ssh-add ~/.ssh/id_rsa

      - name: Add hosts to known_hosts if missing
        run: |
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts  
          
      - name: Initialization and Fetching the Source Code
        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$EMAIL"
          
      - name: Update Git configs
        run: |
          git config --global http.postBuffer 157286400
          git clone --depth=1 git@github.com:nikgapps/updater.git

      - name: Installing Requirements
        run: |
          python3 -m pip install wheel setuptools testresources lxml
          cd updater
          pip3 install -r requirements.txt
          cd ..

      - name: Run steps in batch ${{ matrix.batch }}
        run: |
          start=${{ matrix.batch.start }}
          end=${{ matrix.batch.end }}

          cd updater
          python3 apkmirrorbatch.py -A 13 -S $start -E $end
          cd ..

      # - name: Cleanup known_hosts file
      #   run: |
      #     sed -i '/^frs\.sourceforge\.net /d' ~/.ssh/known_hosts
      #     sed -i '/^gitlab\.com /d' ~/.ssh/known_hosts
