name: NikGapps-Deployment-Docker

on:
  workflow_dispatch:
    inputs:
      android_versions:
        description: 'Comma-separated list of Android versions'
        required: false
        default: '10,11,12.1,13,14'

env:
  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  USER_NAME: ${{ secrets.USER_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  SF_PWD: ${{ secrets.SF_PWD }}
  RELEASE_TYPE: 'stable'
  ENVIRONMENT_TYPE: ${{ secrets.ENVIRONMENT_TYPE }}
  PACKAGE_LIST: core,basic,omni,stock,full,go,addonsets,addons,debloater

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix values
        id: set-matrix
        run: |
          MATRIX_VALUES="${{ github.event.inputs.android_versions }}"
          if [ -z "$MATRIX_VALUES" ]; then
            MATRIX_VALUES="10,11,12.1,13,14"
          fi
          MATRIX_JSON="[$(echo "$MATRIX_VALUES" | sed "s/,/\",\"/g" | sed "s/^/\"/" | sed "s/$/\"/")]"
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
           
  build:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        android_version: ${{fromJson(needs.setup.outputs.matrix)}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup SSH Keys and known_hosts 
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH Keys and known_hosts using kielabokkie
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            ssh-host: frs.sourceforge.net

      - name: Get Website and Release Source
        run: |
          git clone --depth=1 git@github.com:nikgapps/nikgapps.github.io.git
          git clone git@github.com:nikgapps/release.git
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: nikgapps
          password: ${{ secrets.AUTH }}
  
      - name: Pull latest Docker image
        run: docker pull ghcr.io/nikgapps/docker:latest
  
      - name: Building Android ${{ matrix.android_version }} Gapps
        run: |
          mkdir NikGappsProject
          cd NikGappsProject
          MATRIX_VALUES="${{ needs.setup.outputs.matrix }}"
          MATRIX_VALUES=$(echo "$MATRIX_VALUES" | tr -d '[]')
          echo "MATRIX_VALUES=$MATRIX_VALUES"
          IFS=',' read -ra VERSIONS <<< "$MATRIX_VALUES"
          max_version=$(printf "%s\n" "${VERSIONS[@]}" | sort -V | tail -n1)
          echo "Max version is $max_version"
          update_website_flag=$([[ "${{ matrix.android_version }}" == "$max_version" ]] && echo "1" || echo "0")
          
          docker run --rm \
          -e USER_NAME="${{ secrets.USER_NAME }}" \
          -e USER_EMAIL="${{ secrets.EMAIL }}" \
          -e ANDROID_VERSION="${{ matrix.android_version }}" \
          -e PACKAGE_LIST="${{ env.PACKAGE_LIST }}" \
          -e SF_PWD="${{ secrets.SF_PWD }}" \
          -e SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}" \
          -e UPDATE_WEBSITE="$update_website_flag" \
          -e SIGN="1" \
          -e UPLOAD="1" \
          -e RELEASE="0" \
          ghcr.io/nikgapps/docker:latest
          cd ..
      