name: NikGapps Release

on:
  workflow_dispatch:
    inputs:
      android_versions:
        description: 'Comma-separated list of Android versions'
        required: false
        default: '10,11,12.1,13,14'

env:
  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  USER_NAME: ${{ secrets.USER_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  SF_PWD: ${{ secrets.SF_PWD }}
  ENVIRONMENT_TYPE: ${{ secrets.ENVIRONMENT_TYPE }}
  PACKAGE_LIST: core,basic,omni,stock,full,go,addonsets,addons,debloater,removeotascripts
  RELEASE_TYPE: 'stable'
  GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix values
        id: set-matrix
        run: |
          MATRIX_VALUES="${{ github.event.inputs.android_versions }}"
          if [ -z "$MATRIX_VALUES" ]; then
            MATRIX_VALUES="10,11,12.1,13,14"
          fi
          MATRIX_JSON="[$(echo "$MATRIX_VALUES" | sed "s/,/\",\"/g" | sed "s/^/\"/" | sed "s/$/\"/")]"
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
          
  UpdateOverlays:
    needs: Setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        android_version: ${{fromJson(needs.Setup.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup SSH Keys and known_hosts 
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
      - name: Add multiple hosts to known_hosts
        run: |
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts 
          
      - name: Initialization and Fetching the Source Code
        run: |
           git config --global user.name "$USER_NAME"
           git config --global user.email "$EMAIL"
           git config --global http.postBuffer 157286400
      
      - uses: actions/setup-python@v5
         with:
            python-version: '3.12'

      - name: Installing Requirements
        run: |
           sudo apt-get install zipalign
           python3 -m pip install wheel setuptools testresources
           python3 -m pip install NikGapps
           mkdir NikGappsProject
          
      - name: Building Android Overlay
        run: |
           cd NikGappsProject
           nikgapps_overlay -A ${{ matrix.android_version }}
           cd ..

  CopyRepos:
    needs: Setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        android_version: ${{fromJson(needs.Setup.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup SSH Keys and known_hosts 
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
      - name: Add multiple hosts to known_hosts
        run: |
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts 
          
      - name: Initialization and Fetching the Source Code
        run: |
           git config --global user.name "$USER_NAME"
           git config --global user.email "$EMAIL"
           git config --global http.postBuffer 157286400

      - uses: actions/setup-python@v5
         with:
            python-version: '3.12'

      - name: Installing Requirements
        run: |
           sudo apt-get install zipalign
           python3 -m pip install wheel setuptools testresources
           python3 -m pip install NikGapps
           mkdir NikGappsProject
          
      - name: Copy Repos for Android ${{ matrix.android_version }}
        run: |
           cd NikGappsProject
           copy_repos -A ${{ matrix.android_version }}
           cd ..
  
  CacheApks:
    needs: [Setup, UpdateOverlays, CopyRepos]
    runs-on: macos-latest
    strategy:
      matrix:
        android_version: ${{fromJson(needs.Setup.outputs.matrix)}}
        release_type: ["stable", "ondemand"]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup SSH Keys and known_hosts 
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}      
            
      - name: Add multiple hosts to known_hosts
        run: |
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts  
          
      - name: Initialization and Fetching the Source Code
        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$EMAIL"
      
      - uses: actions/setup-python@v5
         with:
            python-version: '3.12'

      - name: Update Git configs and Install Requirements
        run: |
          git config --global http.postBuffer 157286400
          python3 -m pip install wheel setuptools testresources
          python3 -m pip install NikGapps
          mkdir NikGappsProject

      - name: Caching Apks for Android ${{ matrix.android_version }} with ${{ matrix.release_type }}
        env:
          RELEASE_TYPE: ${{ matrix.release_type }}
        run: |
          cd NikGappsProject
          cache --androidVersion ${{ matrix.android_version }} --releaseType $RELEASE_TYPE
          cd ..         

  Build:
    needs: [Setup, UpdateOverlays]
    runs-on: macos-latest
    strategy:
      matrix:
        android_version: ${{fromJson(needs.Setup.outputs.matrix)}}

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Setup SSH Keys and known_hosts 
         uses: webfactory/ssh-agent@v0.9.0
         with:
             ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
             
       - name: Add multiple hosts to known_hosts
         run: |
            ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
            ssh-keyscan gitlab.com >> ~/.ssh/known_hosts 

       - name: Initialization and Fetching the Source Code
         run: |
            git config --global user.name "$USER_NAME"
            git config --global user.email "$EMAIL"

       - uses: actions/setup-python@v5
         with:
            python-version: '3.12'

       - name: Installing Requirements
         run: |
            python3 -m pip install wheel setuptools testresources
            python3 -m pip install NikGapps
            mkdir NikGappsProject
          
       - name: Get Website and Release Source
         run: |
           git clone --depth=1 git@github.com:nikgapps/nikgapps.github.io.git
           git clone git@github.com:nikgapps/release.git

       - name: Update Git configs
         run: |
           git config --global http.postBuffer 157286400
       
       - name: Building Android ${{ matrix.android_version }} Gapps
         run: |
           cd NikGappsProject
           MATRIX_VALUES="${{ needs.Setup.outputs.matrix }}"
           MATRIX_VALUES=$(echo "$MATRIX_VALUES" | tr -d '[]')
           echo "MATRIX_VALUES=$MATRIX_VALUES"
           IFS=',' read -ra VERSIONS <<< "$MATRIX_VALUES"  # Convert comma-separated string to array
           max_version=$(printf "%s\n" "${VERSIONS[@]}" | sort -V | tail -n1)
           echo "Max version is $max_version"
           if [ "${{ matrix.android_version }}" == "$max_version" ]; then
               echo "Updating website in the end"
               nikgapps --sign --upload --release --androidVersion ${{ matrix.android_version }} --packageList $PACKAGE_LIST --updateWebsite
           else
               echo "Not updating website in the end"
               nikgapps --sign --upload --release --androidVersion ${{ matrix.android_version }} --packageList $PACKAGE_LIST
           fi
           cd ..

  upload_config:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup SSH Keys and known_hosts 
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add multiple hosts to known_hosts
        run: |
            ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
            ssh-keyscan gitlab.com >> ~/.ssh/known_hosts 

      - name: Initialization and Fetching the Source Code
        run: |
            git config --global user.name "$USER_NAME"
            git config --global user.email "$EMAIL"

      - uses: actions/setup-python@v5
         with:
            python-version: '3.12'

      - name: Installing Requirements
        run: |
            python3 -m pip install wheel setuptools testresources
            python3 -m pip install NikGapps
            mkdir NikGappsProject
      
      - name: Uploading Config
        run: |
            cd NikGappsProject
            nikgapps_config_upload --androidVersion ${{ github.event.inputs.android_versions }} --upload
            cd ..
